name: "Permanent Interaction Limits"
description: "Makes Temporary Interaction Limits Permanents"
branding:
  icon: slash
  color: red
inputs:
  limit:
    description: 'The limit to set for interactions. Must be one of: existing_users, contributors_only, collaborators_only.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Refresh interaction limit
      shell: bash
      run: |
        gh api repos/${{ github.repository }}/interaction-limits \
          -X PUT \
          -f limit=${{ inputs.limit }} \
          -f expiry=six_months
      env:
        GITHUB_TOKEN: ${{ github.token }}
