name: "Permanent Interaction Limits"
description: "Makes Temporary Interaction Limits Permanent"
branding:
  icon: slash
  color: red
inputs:
  limit:
    description: "The limit to set for interactions. Must be one of: `existing_users`, `contributors_only`, `collaborators_only`. If not provided, the action will use the currently set limit."
    required: false
runs:
  using: composite
  steps:

    - name: Determine interaction limit
      shell: sh
      run: |
        if [ -n "${{ inputs.limit }}" ]; then
          LIMIT_TO_SET="${{ inputs.limit }}"
        else
          LIMIT_TO_SET="$(gh api 'repos/${{ github.repository }}/interaction-limits' --template '{{.limit}}')"
        fi
        echo "LIMIT_TO_SET=${LIMIT_TO_SET}" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Apply interaction limit
      shell: sh
      run: |
        gh api 'repos/${{ github.repository }}/interaction-limits' \
          --method PUT \
          --field "limit=${{ env.LIMIT_TO_SET }}" \
          --field "expiry=six_months"
      env:
        GITHUB_TOKEN: ${{ github.token }}
